version: '3.9'

services:
  db:
    image: mysql:8.0.32
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-gestao-vendas
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge